# Generated by Django 6.0.2 on 2026-02-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Date de commande')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('sales_amount', models.FloatField(verbose_name='Montant des ventes')),
                ('profit', models.FloatField(verbose_name='Profit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-order_date'],
            },
        ),
    ]
